#! /bin/bash
# Enters a file into a database and creates a catalog entry
# 

export CATALOG=`pwd`/test-catalog1
export DATABASE=`pwd`/test-database1
export SRCDIR=${1:?}
# ensure that SRCDIR goes out with a trailing /
SRCDIR=${SRCDIR%/}/

if [ ! -e $CATALOG ]; then 
	{
	echo "# Test database catalog"
	echo "# SHASUM  UUID  OriginalPath/OriginalFilename"
	} > $CATALOG
fi


find ${SRCDIR} -type f -exec bash $(pwd)/register.sh \{\} \;


