#! /bin/bash
# ingest template processor 
# defines the environmental variables that configure the ingest script 

# processing scripts are defined by INGEST_HOME
export INGEST_HOME=${INGEST_HOME:?INGEST_HOME defines directory holding processing scripts}

# dumping data into the database described by DATABASE, CATALOG, and
# LOGFILE
export CATALOG=${CATALOG:?CATALOG: the manifest file, e.g., "/DATA/LOCALWEB/DATA/manifest.txt"}
export DATABASE=${DATABASE:?DATABASE: the database directory, e.g., "/DATA/LOCALWEB/DATA/.DATABASE"}
export LOGFILE=${LOGFILE:?LOGFILE: the log file, e.g., "/DATA/LOCALWEB/DATA/ingest.log"}

# the accession reference and directory structure are defined by
# ACCESSION_DIR 
export ACCESSION_DIR=${ACCESSION_DIR:?The accession reference and directory structure, e.g., "/DATA/LOCALWEB/DATA/ACCESSION"}

export AMSACCFILE="${AMSACCFILE:?Get the next AMS accession number from this file (/DATA/amsaccession)}"

# the source directory is defined by SOURCE_DIR
export SOURCE_DIR="${1:?Provide the source directory as the first argument }"

echo INGEST_HOME=${INGEST_HOME}
echo CATALOG=${CATALOG}
echo DATABASE=${DATABASE}
echo LOGFILE=${LOGFILE}
echo ACCESSION_DIR=${ACCESSION_DIR}
echo AMSACCFILE=${AMSACCFILE}
echo SOURCE_DIR=${SOURCE_DIR}

read -p "Environmental variables are loaded. Complete the ingest (y) or stop (N)? " RESP
RESP=${RESP^^} 
if [ "${RESP:0:1}" == "Y" ]; then
	$INGEST_HOME/ingest.sh ${SOURCE_DIR}
else
	echo Abandoned processing
fi

# vi:se tw=0 :
