#! /bin/bash
# ingest processor for the Library 

# processing scripts are defined by INGEST_HOME
export INGEST_HOME=/DATA/database/INGEST

# dumping data into the database described by DATABASE, CATALOG, and
# LOGFILE
export CATALOG=${CATALOG:-"/DATA/LOCALWEB/DATA/manifest.txt"}
export DATABASE=${DATABASE:-"/DATA/LOCALWEB/DATA/.DATABASE"}
export LOGFILE=${LOGFILE:-"/DATA/LOCALWEB/DATA/ingest.log"}

# the accession refgerence and directory structure are defined by
# ACCESSION_DIR 
export ACCESSION_DIR=${ACCESSION_DIR:-"/DATA/LOCALWEB/DATA/ACCESSION"}

# the source directory is defined by SOURCE_DIR
export SOURCE_DIR="${1:?}"

$INGEST_HOME/ingest.sh ${SOURCE_DIR}

