#! /bin/bash

# read a catalog and link files from the database to a WAF 

# export CATALOG=`pwd`/test-catalog1
# export DATABASE=`pwd`/test-database1

CATALOG=${CATALOG:?}
DATABASE=${DATABASE:?}

export LINKDIR=${1:?}

LINKDIR=${LINKDIR%/}/
DATABASE=${DATABASE%/}

function relpath() { 
  python -c "import os,sys;print(os.path.relpath(*(sys.argv[1:])))" "$@";
}

cat   $CATALOG |
	# tail -n 10 |
	awk -v DB=${DATABASE} -v SD=$LINKDIR -v RRD=$(relpath $DATABASE $LINKDIR) '
		BEGIN{FS="\t"}
		/^#/{next}
		{
		# dir=substr($1,1,2) "/" substr($1,3,2) "/" substr($1,5,2)
		dir=substr($1,1,2) 
		file=substr($1,3)
		# rawfile=substr($0,137)
		rawfile=$NF

		# cmd="ls -l \"" DB "/" dir "/" file "\""

		cmd="dirname \"" rawfile "\""
		# print cmd

		cmd | getline path ;  close(cmd)

		acc=$3 "=" $4

		cmd="mkdir -pv \"" SD "/" acc "/" path "\""
		N=split(path,a,"/")+1
		RD=RRD
		for (i=1;i<=N;i++){RD="../" RD}

		# print cmd
		# print rawfile
		system(cmd) ; close(cmd)

		if (length(file)!=0 && length(rawfile)!=0){
			cmd="ln -sf \"" RD "/" dir "/" file "\" \"" SD "/" acc "/" rawfile"\""
			print cmd
			system(cmd); close(cmd)
			}
		else{
			print "Bad catalog entry: " FNR " (" NR ")" > "/dev/stderr"
			}
		}' 




