#! /bin/bash

# read a catalog and link files from the database to a WAF 

# export CATALOG=`pwd`/test-catalog1
# export DATABASE=`pwd`/test-database1

export LINKDIR=${1:?}

LINKDIR=${LINKDIR%/}/

cat   $CATALOG |
	# tail -n 10 |
	awk -v DB=${DATABASE} -v SD=${LINKDIR} '
		BEGIN{FS="\t"}
		/^#/{next}
		{
		# dir=substr($1,1,2) "/" substr($1,3,2) "/" substr($1,5,2)
		dir=substr($1,1,2) 
		file=substr($1,3)
		# rawfile=substr($0,137)
		rawfile=$NF

		# cmd="ls -l \"" DB "/" dir "/" file "\""

		cmd="dirname \"" rawfile "\""
		# print cmd

		cmd | getline path ;  close(cmd)

		cmd="mkdir -pv \"" SD path "\""

		# print cmd
		# print rawfile
		system(cmd) ; close(cmd)

		if (length(file)!=0 && length(rawfile)!=0){
			cmd="ln -sf \"" DB "/" dir "/" file "\" \"" SD rawfile"\""
			print cmd
			system(cmd); close(cmd)
			}
		else{
			print "Bad catalog entry: " FNR " (" NR ")" > "/dev/stderr"
			}
		}' 




