#! /bin/bash
# Enters a collection into a database and creates a catalog entry
# 

# export CATALOG=`pwd`/test-catalog1
# export DATABASE=`pwd`/test-database1

export INGEST_HOME=${INGEST_HOME:-$(pwd)}

export SRCDIR="${1:?}"

export CATALOG=${CATALOG:?}
export DATABASE=${DATABASE:?}

# ensure that SRCDIR goes out with a trailing /
SRCDIR="${SRCDIR%/}/"


# generate a collection UUID and an accession identifier
# export ACCESSION=`date +"%Y%m%d%H%M%S"`
export COLLECTION=`uuidgen`
export ACCESSION=`date -u +"%Y%m%dT%H%M"`

# echo $SRCDIR
# echo $CATALOG
# echo $DATABASE
# echo $SRCDIR

# echo $ACCESSION
# echo $COLLECTION

# descend through SRCDIR and register all files and directories
# find "${SRCDIR}" -type f -exec bash $(pwd)/register.sh \{\} \;
find "${SRCDIR}" -type f -exec bash ${INGEST_HOME}/register.sh \{\} \;


